### ISSUE TITLE
Atom Documentation

### ISSUE THREAD

**Issue by AnkurRajneta** [AnkurRajneta/Documentation-for-ide-s#15]
- Add documentation for atom text editor

**Comment by Siddhanthota** [comment]
Can you assign this to me?

**Comment by AnkurRajneta** [comment]
Yes you can do this.

**Comment by mynkchaudhry** [comment]
Can I work on this ?

**Comment by Siddhanthota** [comment]
> Yes you can do this.

Can you assign this to me ?
